---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.phpipam default variables
# ================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst


# Basic configuration options [[[
# -------------------------------

# .. envvar:: phpipam__mode [[[
#
# What parts of the "phpIPAM stack" to enable:
#
# - ``webui``: configure the Web interface
#
# - ``scripts``: configure phpipam-scripts
#
phpipam__mode: [ 'webui', 'scripts' ]

                                                                   # ]]]
# .. envvar:: phpipam__dependencies [[[
#
# Should phpipam role manage it's own dependencies?
phpipam__dependencies: True
                                                                   # ]]]

# .. envvar:: phpipam__php__dependent_packages [[[
#
# List of PHP packages to install using :ref:`debops.php` role.
phpipam__php__dependent_packages:
  - 'mysql'
  - 'gmp'
  - 'gd'
  - 'curl'
  - 'mcrypt'
  - 'ldap'
  - 'php-pear'
                                                                   # ]]]
# .. envvar:: phpipam__domain [[[
#
# Domain on which phpIPAM is configured in nginx
phpipam__domain: [ 'ipam.{{ ansible_domain }}' ]

                                                                   # ]]]
# .. envvar:: phpipam__nginx_auth_realm [[[
#
# FIXME(yaml4rst): Describe what this variable is doing.
phpipam__nginx_auth_realm: 'IPAM access is restricted'

                                                                   # ]]]
# .. envvar:: phpipam__nginx_access_policy [[[
#
# FIXME(yaml4rst): Describe what this variable is doing.
phpipam__nginx_access_policy: ''

                                                                   # ]]]
# .. envvar:: phpipam__database_schema [[[
#
# phpIPAM database schema loaded by Ansible
phpipam__database_schema: '{{ phpipam__git_checkout + "/db/SCHEMA.sql" }}'
                                                                   # ]]]

# .. envvar:: phpipam__php5_pool [[[
#
# Configuration for php5-fpm pool
phpipam__php5_pool:
  enabled: True
  name: 'phpipam'
  user: '{{ phpipam__user }}'
  group: '{{ phpipam__group }}'
                                                                   # ]]]

# .. envvar:: phpipam__nginx_upstream_php5 [[[
#
# nginx configuration - PHP5 upstream
phpipam__nginx_upstream_php5:
  enabled: True
  name: 'php5_phpipam'
  type: 'php5'
  php5: 'phpipam'
                                                                   # ]]]

# .. envvar:: phpipam__nginx_server [[[
#
# nginx configuration - phpIPAM server
phpipam__nginx_server:
  by_role: 'debops.phpipam'
  enabled: True
  type: 'php5'
  name: '{{ phpipam__domain }}'
  root: '{{ phpipam__git_checkout }}'
  access_policy: '{{ phpipam__nginx_access_policy }}'
  auth_basic_realm: '{{ phpipam__nginx_auth_realm }}'
  php5: 'php5_phpipam'

  error_pages:
    '400': '/index.php?page=error&section=400'
    '401': '/index.php?page=error&section=401'
    '403': '/index.php?page=error&section=403'
    '404': '/index.php?page=error&section=404'
    '500': '/index.php?page=error&section=500'

  location:
    '/api': |
      try_files $uri $uri/ /api/index.php?$args =404;

    '/': |
      rewrite ^/login/dashboard/$                 /dashboard/ redirect;
      rewrite ^/logout/dashboard/$                /dashboard/ redirect;
      rewrite ^/tools/search/(.*)/(.*)/(.*)/(.*)$ /index.php?page=tools&section=search&addresses=$1&subnets=$2&vlans=$3&ip=$4 last;
      rewrite ^/(.*)/(.*)/(.*)/(.*)/(.*)/$        /index.php?page=$1&section=$2&subnetId=$3&sPage=$4&ipaddrid=$5 last;
      rewrite ^/(.*)/(.*)/(.*)/(.*)/$             /index.php?page=$1&section=$2&subnetId=$3&sPage=$4 last;
      rewrite ^/(.*)/(.*)/(.*)/$                  /index.php?page=$1&section=$2&subnetId=$3 last;
      rewrite ^/(.*)/(.*)/$                       /index.php?page=$1&section=$2 last;
      rewrite ^/(.*)/$                            /index.php?page=$1 last;
      try_files $uri $uri/ $uri.html $uri.htm /index.html /index.htm =404;
# ]]]

# User, group, database configuration [[[
# ---------------------------------------

# .. envvar:: phpipam__user [[[
#
# System user and group for phpIPAM application
phpipam__user: 'phpipam'

                                                                   # ]]]
# .. envvar:: phpipam__group [[[
#
# FIXME(yaml4rst): Describe what this variable is doing.
phpipam__group: 'phpipam'

                                                                   # ]]]
# .. envvar:: phpipam__home [[[
#
# FIXME(yaml4rst): Describe what this variable is doing.
phpipam__home: '{{ (ansible_local.root.home
                   if (ansible_local|d() and ansible_local.root|d() and
                       ansible_local.root.home|d())
                   else "/var/local") + "/" + phpipam__user }}'

                                                                   # ]]]
# .. envvar:: phpipam__database_user [[[
#
# phpIPAM MySQL database configuration
phpipam__database_user: 'phpipam'

                                                                   # ]]]
# .. envvar:: phpipam__database_host [[[
#
# FIXME(yaml4rst): Describe what this variable is doing.
phpipam__database_host: 'localhost'

                                                                   # ]]]
# .. envvar:: phpipam__database_name [[[
#
# FIXME(yaml4rst): Describe what this variable is doing.
phpipam__database_name: 'phpipam'

                                                                   # ]]]
# .. envvar:: phpipam__database_password [[[
#
# FIXME(yaml4rst): Describe what this variable is doing.
phpipam__database_password: "{{ lookup('password', secret + '/credentials/' + ansible_fqdn + '/phpipam/mysql/' + phpipam__database_user + '/password length=30') }}"

                                                                   # ]]]
                                                                   # ]]]
# Base application directories [[[
# --------------------------------

# .. envvar:: phpipam__src [[[
#
# Base path for git bare repository with phpIPAM source
phpipam__src: '{{ (ansible_local.root.src
                  if (ansible_local|d() and ansible_local.root|d() and
                      ansible_local.root.src|d())
                  else "/usr/local/src") + "/" + phpipam__user }}'

                                                                   # ]]]
# .. envvar:: phpipam__www [[[
#
# Base web root directory for phpIPAM website
phpipam__www: '{{ (ansible_local.nginx.www if (ansible_local is defined and ansible_local.nginx is defined and ansible_local.nginx.www is defined) else "/srv/www") + "/" + phpipam__user }}'

                                                                   # ]]]
# .. envvar:: phpipam__webserver_user [[[
#
# phpIPAM webserver user (needs read-only access to the website code)
phpipam__webserver_user: '{{ ansible_local.nginx.user if (ansible_local is defined and ansible_local.nginx is defined and ansible_local.nginx.user is defined) else "www-data" }}'

                                                                   # ]]]
                                                                   # ]]]
# Git repository and checkout [[[
# -------------------------------

# .. envvar:: phpipam__git_repo [[[
#
# phpIPAM source repository
phpipam__git_repo: 'https://github.com/debops/phpipam.git'

                                                                   # ]]]
# .. envvar:: phpipam__git_dest [[[
#
# phpIPAM source directory on the host
phpipam__git_dest: '{{ phpipam__src + "/" + phpipam__git_repo.split("://")[1] }}'

                                                                   # ]]]
# .. envvar:: phpipam__git_version [[[
#
# phpIPAM git branch to deploy
phpipam__git_version: 'master'

                                                                   # ]]]
# .. envvar:: phpipam__git_checkout [[[
#
# Default path where phpIPAM source files will be deployed
phpipam__git_checkout: '{{ phpipam__www + "/sites/" + phpipam__domain[0] + "/public" }}'

                                                                   # ]]]
                                                                   # ]]]
# Other variables [[[
# -------------------

# .. envvar:: phpipam__php_session_name [[[
#
# Custom PHP session name
phpipam__php_session_name: "{{ lookup('password', secret + '/credentials/' + ansible_fqdn + '/phpipam/php_session_name chars=hexdigits length=30') }}"

                                                                   # ]]]
                                                                   # ]]]

# phpipam-scripts [[[

# .. envvar:: phpipam__scripts_git_repo [[[
#
# phpIPAM scripts source repository
phpipam__scripts_git_repo: 'https://github.com/debops/phpipam-scripts'

                                                                   # ]]]
# .. envvar:: phpipam__scripts_git_dest [[[
#
# phpIPAM scripts source directory on the host
phpipam__scripts_git_dest: '{{ "/usr/local/src/phpipam/" + phpipam__scripts_git_repo.split("://")[1] }}'

                                                                   # ]]]
# .. envvar:: phpipam__scripts_git_version [[[
#
# phpIPAM scripts git branch to deploy
phpipam__scripts_git_version: 'master'

                                                                   # ]]]
# .. envvar:: phpipam__scripts_database_user [[[
#
# Database configuration for phpipam scripts
phpipam__scripts_database_user: '{{ phpipam__database_user }}'

                                                                   # ]]]
# .. envvar:: phpipam__scripts_database_host [[[
#
# FIXME(yaml4rst): Describe what this variable is doing.
phpipam__scripts_database_host: '{{ phpipam__database_host }}'

                                                                   # ]]]
# .. envvar:: phpipam__scripts_database_name [[[
#
# FIXME(yaml4rst): Describe what this variable is doing.
phpipam__scripts_database_name: '{{ phpipam__database_name }}'

                                                                   # ]]]
# .. envvar:: phpipam__scripts_database_password [[[
#
# FIXME(yaml4rst): Describe what this variable is doing.
phpipam__scripts_database_password: '{{ phpipam__database_password }}'

                                                                   # ]]]
# .. envvar:: phpipam__scripts_config_sections [[[
#
# List of phpIPAM sections to include in generated default configuration. If
# none are specified, all sections will be included.
phpipam__scripts_config_sections: []

                                                                   # ]]]
# .. envvar:: phpipam__scripts_config_subnets [[[
#
# List of phpIPAM subnets to include in generated default configuration. If
# none are specified, all subnets will be included.
phpipam__scripts_config_subnets: []

                                                                   # ]]]
# .. envvar:: phpipam__scripts_config_output [[[
#
# Default configuration file location
phpipam__scripts_config_output: '/etc/dhcp/dhcpd-hosts.conf'

                                                                   # ]]]
# .. envvar:: phpipam__scripts_config_restart_command [[[
#
# A command to issue after the configuration file is generated and changes were
# noticed.
phpipam__scripts_config_restart_command: '/etc/init.d/isc-dhcp-server restart'

                                                                   # ]]]
# .. envvar:: phpipam__scripts_config_groups [[[
#
# Default configuration for phpipam-hosts script. It will create
# a ``/etc/dhcp/dhcpd-hosts.conf`` file with all hosts configured in phpIPAM,
# or just the sections/subnets specified above. If any changes are detected,
# DHCP server (by default ISC DHCP) will be restarted.
phpipam__scripts_config_groups:
  'hosts':
    sections: '{{ phpipam__scripts_config_sections }}'
    subnets: '{{ phpipam__scripts_config_subnets }}'
    active: 'true'
    reserved: 'false'
    offline: 'false'
    dhcp: 'false'
    output: '{{ phpipam__scripts_config_output }}'
    restart_command: '{{ phpipam__scripts_config_restart_command }}'
    restart: 'true'

                                                                   # ]]]
# .. envvar:: phpipam__scripts_cron_period [[[
#
# phpipam-hosts regeneration period in minutes (cron format)
phpipam__scripts_cron_period: '*/5'
                                                                   # ]]]
# ]]]
# ]]]
