---

- name: Restart gunicorn for etesync
  service:
    name: 'gunicorn@etesync'
    state: 'restarted'
  when: (ansible_local|d() and ansible_local.gunicorn|d() and
         ansible_local.gunicorn.installed|bool)
