---

- name: Set attributes in the {{ database.name }} database
  ldap_attr:
    dn: '{{ database.dn }}'
    name: '{{ item.attribute | d(item.attr | d(item.name)) }}'
    values: '{{ item.value
                if (item.value is string)
                else (item.value
                      | selectattr("state", "equalto", "present")
                      | map(attribute="name") | list) }}'
    state: '{{ item.state }}'
  loop: '{{ database.attributes }}'
  loop_control:
    label: '{{ {"state": item.state,
                "attribute": (item.attribute | d(item.attr | d(item.name))),
                "value": (item.value
                          if (item.value is string)
                          else (item.value
                                | selectattr("state", "equalto", "present")
                                | map(attribute="name") | list))} }}'
  when: database.attributes|d() and item.state not in [ 'ignore' ]
  no_log: '{{ item.no_log | d(False) }}'
