---

- name: Configure LDAP Access Control List
  ldap_attr:
    dn: 'olcDatabase={1}{{ slapd_backend }},cn=config'
    name: 'olcAccess'
    values: '{{ lookup("template", "lookup/slapd_ldap_access_control_list.j2") | from_yaml }}'
    state: 'exact'
