---

- name: '{{ item.name }}'
  ldap_entry:
    dn:          '{{ item.dn if (item.dn is string) else item.dn | join(",") }}'
    objectClass: '{{ item.objectClass }}'
    attributes:  '{{ item.attributes | d(omit) }}'
    state:       '{{ item.state }}'
  when: item.objectClass|d() and item.state not in [ 'init', 'ignore' ]
  no_log: '{{ item.no_log | d(False) }}'

- name: '{{ item.name }}'
  ldap_attrs:
    dn:         '{{ item.dn if (item.dn is string) else item.dn | join(",") }}'
    attributes: '{{ item.attributes }}'
    state:      '{{ item.state }}'
  when: not item.objectClass|d() and item.state not in [ 'init', 'ignore' ]
  no_log: '{{ item.no_log | d(False) }}'
