# Copyright (C) 2023-2023 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only
#
[tool.codespell]
skip = ".venv,*/includes/global.rst,*LICENSES*"
# 'alse' is to ignore literal regex '[Ff]alse'
# hass is home assistant contraction
ignore-words-list = "referer, referers, alse, keyserver, keyservers, hass"
exclude-file = ".codespell.exclude"
