---
# Copyright (C) 2021 Sorin Sbarnea <ssbarnea@redhat.com>
# Copyright (C) 2021 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

# List of Ansible Collections required by the DebOps Collection

collections:
  - ansible.posix
  - community.crypto
  - community.general
  - community.libvirt
  - community.mysql
  - community.postgresql
  - community.rabbitmq
