---
# Copyright (C) 2021 Dr. Serge Victor <https://dr.sergevictor.eu/>
# Copyright (C) 2021 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Restart Telegraf
  service:
    name: "telegraf"
    state: "restarted"
