---

- name: Load persistent Postfix configuration
  set_fact:
    postfix__env_persistent_maincf:   '{{ lookup("template", "lookup/postfix__env_persistent_maincf.j2")   | from_yaml }}'
    postfix__env_persistent_mastercf: '{{ lookup("template", "lookup/postfix__env_persistent_mastercf.j2") | from_yaml }}'

- name: Prepare Postfix environment
  set_fact:
    postfix__env_active_services: '{{ lookup("template", "lookup/postfix__env_active_services.j2") | from_yaml }}'
    postfix__secret__directories: '{{ lookup("template", "lookup/postfix__secret__directories.j2") | from_yaml }}'
