---
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Copyright (C) 2014-2017 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2014-2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Import DebOps global handlers
  ansible.builtin.import_role:
    name: 'global_handlers'

- name: Install Java packages
  ansible.builtin.package:
    name: '{{ q("flattened", (java__base_packages
                              + java__jdk_packages
                              + java__packages
                              + java__group_packages
                              + java__host_packages
                              + java__dependent_packages)) }}'
    state: 'present'
  register: java__register_packages
  until: java__register_packages is succeeded

- name: Update Java alternatives
  ansible.builtin.command: 'update-java-alternatives -s {{ java__alternatives }}'
  when: java__alternatives|d()

- name: Make sure that Ansible local facts directory exists
  ansible.builtin.file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save Java local facts
  ansible.builtin.template:
    src: 'etc/ansible/facts.d/java.fact.j2'
    dest: '/etc/ansible/facts.d/java.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: [ 'Refresh host facts' ]
  tags: [ 'meta::facts' ]

- name: Update Ansible facts if they were modified
  ansible.builtin.meta: 'flush_handlers'
