---

- name: Make sure required POSIX group exist
  group:
    name: '{{ postldap__vmail_posix_group |
              d(postldap__vmail_posix_user) }}'
    state: 'present'
    system: True

- name: Make sure required POSIX system account exist
  user:
    name: '{{ postldap__vmail_posix_user }}'
    state: 'present'
    comment: 'Postfix Virtual Mail user'
    group: '{{ postldap__vmail_posix_group |
               d(postldap__vmail_posix_user) }}'
    home: '{{ postldap__mailbox_base }}'
    create_home: True
    system: True
    shell: '/usr/sbin/nologin'
    skeleton: null

- name: "Make sure vmail home directory ({{ postldap__mailbox_base }}) exists with restrictive permissions"
  file:
    dest: '{{ postldap__mailbox_base }}'
    state: 'directory'
    owner: '{{ postldap__vmail_posix_user }}'
    group: '{{ postldap__vmail_posix_group }}'
    mode: '0750'

- name: Get vmail group info
  getent:
    database: 'group'
    split: ':'
    key: '{{ postldap__vmail_posix_group }}'

- name: Get vmail passwd info
  getent:
    database: 'passwd'
    split: ':'
    key: '{{ postldap__vmail_posix_user }}'
