---

- name: Make sure required POSIX groups exist
  group:
    name: '{{ item.group | d(item.name) }}'
    state: present
    system: '{{ item.system | d(True) | bool }}'
  with_flattened:
    - '{{ postfix_virtual_ldap__system_users }}'
  when: 'item.state|d("present") != "absent" and item.name|d() and item.home|d()'

- name: Make sure required POSIX system accounts exist
  user:
    name: '{{ item.name }}'
    state: 'present'
    comment: '{{ item.comment | d("Postfix Virtual Mail user") }}'
    group: '{{ item.group | d(item.name) }}'
    home: '{{ item.home }}'
    create_home: '{{ item.create_home | d(True) | bool }}'
    system: '{{ item.system | d(True) | bool }}'
    shell: '{{ item.shell | d("/usr/sbin/nologin") }}'
    skeleton: '{{ item.skeleton | d(None) }}'
  with_flattened:
    - '{{ postfix_virtual_ldap__system_users }}'
  when: 'item.state|d("present") != "absent" and item.name|d() and item.home|d()'

- name: "Make sure vmail home directory ({{ postfix_virtual_ldap__mailbox_base }}) exists with restrictive permissions"
  file:
    dest: '{{ postfix_virtual_ldap__mailbox_base }}'
    state: 'directory'
    owner: '{{ postfix_virtual_ldap__vmail_posix_user }}'
    group: '{{ postfix_virtual_ldap__vmail_posix_group }}'
    mode: '0750'

- name: Get vmail group info
  getent:
    database: 'group'
    split: ':'
    key: '{{ postfix_virtual_ldap__vmail_posix_group }}'

- name: Get vmail passwd info
  getent:
    database: 'passwd'
    split: ':'
    key: '{{ postfix_virtual_ldap__vmail_posix_user }}'

- name: Make sure 'postfix/ldap' directory exists
  file:
    dest: '/etc/postfix/ldap'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
