---
# Copyright (C) 2017 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2017 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Deploy volkszaehler with Apache
  import_playbook: volkszaehler-apache.yml

- name: Deploy volkszehler with nginx
  import_playbook: volkszaehler-nginx.yml
