---
# vim: foldmarker=[[[,]]]:foldmethod=marker

- name: Check default ldap config exists
  command: php --file "{{ owncloud__app_home }}/occ" ldap:show-config ""
  changed_when: False
  when: (not ansible_check_mode)
  register: owncloud__register_ldap_default_config_exits
  become: True
  become_user: '{{ owncloud__app_user }}'

- name: Create empty LDAP config
  command: php --file "{{ owncloud__app_home }}/occ" ldap:create-empty-config
  become: True
  become_user: '{{ owncloud__app_user }}'
  when: ((not ansible_check_mode) and 'Invalid configID' in owncloud__register_ldap_default_config_exits.stdout|d(""))

- name: Set LDAP password
  command: php --file "{{ owncloud__app_home }}/occ"
               ldap:set-config "" ldapAgentPassword "{{ owncloud__ldap_bindpw }}"
  changed_when: False
  become: True
  become_user: '{{ owncloud__app_user }}'
  no_log: True
  when: ((not ansible_check_mode) and owncloud__ldap_bindpw is string and owncloud__ldap_bindpw|length > 0)

- name: Set LDAP parameters
  command: php --file "{{ owncloud__app_home }}/occ" ldap:set-config "" "{{ item.key }}" "{{ item.value }}"
  changed_when: False
  become: True
  become_user: '{{ owncloud__app_user }}'
  when: ((not ansible_check_mode) and
         ('Invalid configID' in owncloud__register_ldap_default_config_exits.stdout|d("") or
         owncloud_ldap_update_settings|bool))
  with_dict: '{{ owncloud__ldap_conf_map }}'

## FIXME: occ ldap:test-config ''
## Returns 'The configuration is invalid. Please have a look at the logs for further details.' if invalid
## Returns 'The configuration is valid and the connection could be established!' if valid
## Note: Exit code is always 0!!
