---
# Copyright (C) 2020 CipherMail B.V. <https://www.ciphermail.com/>
# Copyright (C) 2020 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Manage PowerDNS authoritative server
  hosts: [ 'debops_service_pdns' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: etc_services
      tags: [ 'role::etc_services', 'skip::etc_services' ]
      etc_services__dependent_list:
        - '{{ pdns__etc_services__dependent_list }}'
      when: pdns__api or pdns__metrics

    - role: ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ pdns__ferm__dependent_rules }}'

    - role: postgresql
      tags: [ 'role::postgresql', 'skip::postgresql' ]
      postgresql__dependent_roles:
        - '{{ pdns__postgresql__dependent_roles }}'
      when: ('gpgsql' in pdns__backends)

    - role: nginx
      tags: [ 'role::nginx', 'skip::nginx' ]
      nginx__dependent_servers:
        - '{{ pdns__nginx__dependent_servers }}'
      when: pdns__nginx_allow and (pdns__api or pdns__metrics)

    - role: pdns
      tags: [ 'role::pdns', 'skip::pdns' ]
