---

- name: Manage phpIPAM service
  hosts: [ 'debops_service_phpipam', 'debops_phpipam' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.php/env
      tags: [ 'role::php', 'role::apt_preferences', 'role::logrotate' ]

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences', 'skip::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ php__apt_preferences__dependent_list }}'
        - '{{ nginx__apt_preferences__dependent_list }}'

    - role: debops.logrotate
      tags: [ 'role::logrotate' ]
      logrotate__dependent_config:
        - '{{ php__logrotate__dependent_config }}'

    - role: debops.php
      php__dependent_packages:
        - '{{ phpipam__php__dependent_packages }}'
      php__dependent_pools: [ '{{ phpipam__php5_pool }}' ]
      when: ((phpipam__dependencies is defined and phpipam__dependencies) and
        (phpipam_mode is defined and 'webui' in phpipam_mode))

    - role: debops.ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ nginx__ferm__dependent_rules }}'

    - role: debops.nginx
      nginx_servers: [ '{{ phpipam_nginx_server }}' ]
      nginx_upstreams: [ '{{ phpipam_nginx_upstream_php5 }}' ]
      when: ((phpipam_dependencies is defined and phpipam_dependencies) and
        (phpipam_mode is defined and 'webui' in phpipam_mode))
      tags: nginx

    - role: debops.phpipam
      tags: [ 'role::phpipam', 'skip::phpipam' ]
