---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2021 Dr. Serge Victor <https://dr.sergevictor.eu/>
# .. Copyright (C) 2021 DebOps <https://debops.org/>
# .. SPDX-License-Identifier: GPL-3.0-or-later

# .. _telegraf__ref_defaults:

# debops.telegraf default variables
# =================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../../includes/global.rst


# APT packages [[[
# ------------

# .. envvar:: telegraf__base_packages [[[
#
# List of the default APT packages to install Telegraf.
telegraf__base_packages: [ 'telegraf' ]

                                                                   # ]]]
# .. envvar:: telegraf__packages [[[
#
# List of additional APT packages ta install with Telegraf.
telegraf__packages: []
                                                                   # ]]]
                                                                   # ]]]
# Telegraf configuration directory [[[
# --------------------------------

# The variable below defines the contents of the
# :file:`/etc/telegraf/telegraf.d` configuration directory.
# Definition of minimum one input and one output is mandatory.

# .. envvar:: telegraf__configuration [[[
#
# All plugins you want to run on all hosts.
telegraf__configuration:

  - name: 'input_influxdb_local'
    config: |
      [[inputs.influxdb_v2_listener]]
        service_address = "127.0.0.1:38086"
    state: 'present'

  - name: 'output_discard'
    config: |
      [[outputs.discard]]
    state: 'present'

                                                                   # ]]]
# .. envvar:: telegraf__group_configuration [[[
#
# All plugins you want to run in group.
telegraf__group_configuration: []

                                                                   # ]]]
# .. envvar:: telegraf_host_configuration [[[
#
# All plugins you want to run in a particulr host.
telegraf__host_configuration: []

                                                                   # ]]]
# .. envvar:: telegraf__combined_configuration [[[
#
# Full list of Telegraf configuration options passed to the
# configuration template dir.
telegraf__configuration_combined: '{{ telegraf__configuration
                                      + telegraf__group_configuration
                                      + telegraf__host_configuration }}'
                                                                   # ]]]
                                                                   # ]]]
# Configuration for other Ansible roles [[[
# -------------------------------------

# .. envvar:: telegraf__influxdata__dependent_packages [[[
#
# Configuration for the :ref:`debops.influxdata` Ansible role.
telegraf__influxdata__dependent_packages:
  - '{{ telegraf__base_packages }}'
  - '{{ telegraf__packages }}'
                                                                   # ]]]
                                                                   # ]]]
