---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2020 DebOps <https://debops.org/>
# .. SPDX-License-Identifier: GPL-3.0-or-later

# .. _telegraf__ref_defaults:

# debops.telegraf default variables
# ========================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../../includes/global.rst


# APT packages [[[
# -------------------------------

# .. envvar:: telegraf__base_packages [[[
#
# List of the default APT packages to install Telegraf.
telegraf__base_packages: [ 'telegraf' ]

                                                                   # ]]]
# .. envvar:: telegraf__packages [[[
#
# List of additional APT packages ta install with Telegraf.
telegraf__packages: []

                                                                   # ]]]
                                                                   # ]]]

# Telegraf configuration directory [[[
# --------------------------------

# The variable below defines the contents of the
# :file:`/etc/telegraf/telegraf.d` configuration directory.
# Definition of minimum one input and one output is mandatory.

# .. envvar:: telegraf__plugins_input [[[
#
# Input plugins list
telegraf__plugins_input:
  - '{{ telegraf__input_proxy_default }}'
                                                                   # ]]]

# .. envvar:: telegraf__plugins_output [[[
#
# Output plugins list
telegraf__plugins_output:
  - '{{ telegraf__output_proxy_default }}'

                                                                   # ]]]

# .. envvar:: telegraf__plugins_aggregator [[[
#
# Aggregator plugins list
telegraf__plugins_aggregator: []

                                                                   # ]]]

# .. envvar:: telegraf__plugins_processor [[[
#
# Processor plugins list
telegraf__plugins_processor: []

                                                                   # ]]]

# .. envvar:: telegraf__input_proxy_default [[[
#
# Default dummy proxy input
telegraf__input_proxy_default:
  name: 'input_proxy_default'
  content: |
    [[inputs.influxdb_v2_listener]]
      service_address = ":38086"
  state: 'present'

                                                                   # ]]]

# .. envvar:: telegraf__output_proxy_default [[[
#
# Default dummy proxy output
telegraf__output_proxy_default:
  name: 'output_proxy_default'
  content: |
    [[outputs.influxdb_v2]]
  state: 'present'
                                                                   # ]]]

# .. envvar:: telegraf__combined_configuration [[[
#
# Full list of Telegraf configuration options passed to the
# configuration template dir.
telegraf__plugins_combined: '{{ telegraf__plugins_input +
                                  telegraf__plugins_output +
                                  telegraf__plugins_aggregator +
                                  telegraf__plugins_processor }}'

                                                                   # ]]]
                                                                   # ]]]
# Configuration for other Ansible roles [[[
# -----------------------------------------

# .. envvar:: telegraf__influxdata__dependent_packages [[[
#
# Configuration for the :ref:`debops.influxdata` Ansible role.
telegraf__influxdata__dependent_packages:
  - '{{ telegraf__base_packages }}'
  - '{{ telegraf__packages }}'

                                                                   # ]]]
                                                                   # ]]]
