---
# Copyright (C) 2021-2022 Berkhan Berkdemir <berkhan@tekdanisman.com>
# Copyright (C) 2015-2022 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Import custom Ansible plugins
  ansible.builtin.import_role:
    name: 'ansible_plugins'

- name: Import DebOps global handlers
  ansible.builtin.import_role:
    name: 'global_handlers'

- name: Import DebOps secret role
  ansible.builtin.import_role:
    name: 'secret'

- name: Create required UNIX system group
  ansible.builtin.group:
    name: '{{ miniflux__group }}'
    state: 'present'
    system: True

- name: Create required UNIX system account
  ansible.builtin.user:
    name: '{{ miniflux__user }}'
    group: '{{ miniflux__group }}'
    append: True
    home: '{{ miniflux__home }}'
    comment: '{{ miniflux__comment }}'
    shell: '{{ miniflux__shell }}'
    skeleton: '/dev/null'
    state: 'present'
    system: True

- name: Install systemd configuration files
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    mode: '0644'
  loop:
    - 'etc/systemd/system/miniflux.service'
    - 'etc/miniflux.conf'
  notify: [ 'Reload service manager' ]

- name: Start and enable Miniflux service
  ansible.builtin.service:
    name: 'miniflux'
    state: 'started'
    enabled: True
