---

dependencies: []

galaxy_info:

  author: 'Patryk Ściborek'
  description: 'Configure InfluxData APT repositories'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.9.0'
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - zesty
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
  galaxy_tags:
    - clustering
    - database
    - nosql
    - search
    - influxdb
    - telegraf
    - chronograf
    - kapacitor
