---
# Copyright (C) 2018 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2018 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Import DebOps global handlers
  ansible.builtin.import_role:
    name: 'global_handlers'

- import_role:
    name: 'secret'

- name: Set dbconfig configuration for Icinga database
  ansible.builtin.debconf:
    name: 'icinga2-{{ icinga_db__feature }}'
    question: '{{ item.question }}'
    vtype: '{{ item.vtype }}'
    value: '{{ item.value }}'
  with_items: '{{ icinga_db__dbconfigs }}'
  when: icinga_db__icinga_installed|bool and
        icinga_db__type != 'unknown' and
        item.state|d('present') == 'present'
  no_log: '{{ item.vtype == "password" }}'
  changed_when: False

- name: Install required packages
  ansible.builtin.package:
    name: '{{ lookup("flattened",
                     (icinga_db__base_packages + icinga_db__packages),
                     wantlist=True) }}'
    state: 'present'
  register: icinga_db__register_packages
  until: icinga_db__register_packages is succeeded
  notify: [ 'Check icinga2 configuration and restart' ]
  when: icinga_db__icinga_installed | bool and
        icinga_db__type != 'unknown'

- name: Import Icinga IDO database on installation into PostgreSQL
  postgresql_db:
    name: '{{ icinga_db__database }}'
    state: 'restore'
    login_host: '{{ icinga_db__host }}'
    login_password: '{{ icinga_db__password }}'
    login_user: '{{ icinga_db__user }}'
    target: '{{ icinga_db__postgresql_schema }}'
  when: icinga_db__type == 'postgresql' and
        icinga_db__init|bool

- name: Import Icinga IDO database on installation into MariaDB
  mysql_db:
    name: '{{ icinga_db__database }}'
    state: 'import'
    login_host: '{{ icinga_db__host }}'
    login_password: '{{ icinga_db__password }}'
    login_user: '{{ icinga_db__user }}'
    target: '{{ icinga_db__mariadb_schema }}'
  when: icinga_db__type == 'mariadb' and
        icinga_db__init|bool

- name: Ensure that IDO feature is enabled
  ansible.builtin.file:
    path: '/etc/icinga2/features-enabled/{{ icinga_db__feature }}.conf'
    src: '../features-available/{{ icinga_db__feature }}.conf'
    state: 'link'
    mode: '0600'
  notify: [ 'Check icinga2 configuration and restart' ]
  when: icinga_db__icinga_installed | bool and
        icinga_db__feature != 'unknown'

- name: Make sure that Ansible local facts directory exists
  ansible.builtin.file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save Icinga database local facts
  ansible.builtin.template:
    src: 'etc/ansible/facts.d/icinga_db.fact.j2'
    dest: '/etc/ansible/facts.d/icinga_db.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: [ 'Refresh host facts' ]
  tags: [ 'meta::facts' ]

- name: Update Ansible facts if they were modified
  ansible.builtin.meta: 'flush_handlers'
