{# Copyright (C) 2020 Maciej Delmanowski <drybjed@gmail.com>
 # Copyright (C) 2020 DebOps <https://debops.org/>
 # SPDX-License-Identifier: GPL-3.0-or-later
 #}
# This file contains the default DebOps configuration options. It will be
# parsed by Jinja template engine before being passed over to the Python's
# TOML parser. The 'env' dictionary contains the environment variables.

[binaries]

# Path to binary which will be used to execute 'ansible-playbook' command.
# By default it will rely on the system's $PATH.
ansible-playbook = "{{ env['DEBOPS_CMD_ANSIBLE_PLAYBOOK'] | d('ansible-playbook') }}"
