---

# ---- System Account ----

- name: Create Roundcube group
  group:
    name: '{{ roundcube__group }}'
    system: True
    state: 'present'

- name: Create Roundcube user
  user:
    name: '{{ roundcube__user }}'
    group: '{{ roundcube__group }}'
    home: '{{ roundcube__home }}'
    shell: '{{ roundcube__shell }}'
    comment: '{{ roundcube__comment }}'
    system: True
    state: 'present'


# ---- Deployment ----

- name: Create required Roundcube directories
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: '{{ roundcube__user }}'
    group: '{{ roundcube__group }}'
    mode: '0755'
  loop:
    - '{{ roundcube__src }}'
    - '{{ roundcube__git_dir  | dirname }}'
    - '{{ roundcube__git_dest | dirname }}'

- name: Clone Roundcube source from upstream repository
  git:
    repo: '{{ roundcube__git_repo }}'
    dest: '{{ roundcube__git_dest }}'
    version: '{{ roundcube__git_version }}'
    separate_git_dir: '{{ roundcube__git_dir }}'
    verify_commit: True
  become: True
  become_user: '{{ roundcube__user }}'

- name: Read PHP composer template
  command: cat {{ roundcube__git_dest }}/composer.json-dist
  become: True
  become_user: '{{ roundcube__user }}'
  register: roundcube__register_composer_json
  changed_when: False


# ---- Post deployment ----

- name: Generate PHP composer.json
  template:
    src: 'srv/www/sites/composer.json.j2'
    dest: '{{ roundcube__git_dest }}/composer.json'
    owner: 'root'
    group: '{{ roundcube__group }}'
    mode: '0640'

- name: Install missing PHP packages via Composer
  composer:
    command: 'install'
    working_dir: '{{ roundcube__git_dest }}'
  become: True
  become_user: '{{ roundcube__user }}'
  register: roundcube__register_composer
  until: roundcube__register_composer is succeeded

- name: Install Javascript packages
  command: bin/install-jsdeps.sh
  args:
    chdir: '{{ roundcube__git_dest }}'
  become: True
  become_user: '{{ roundcube__user }}'
  # The script does not have any useful status output
  # FIXME: Find better way to make this task idempotent
  changed_when: False

- name: Enable cleandb.sh Cron job
  cron:
    name: Roundcube daily database housekeeping
    user: '{{ roundcube__user }}'
    job: '{{ roundcube__git_dest }}/bin/cleandb.sh'
    cron_file: 'roundcube'
    hour: '22'
    minute: '0'
