---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# .. Copyright (C) 2014-2017 Maciej Delmanowski <drybjed@gmail.com>
# .. Copyright (C) 2014-2022 DebOps <https://debops.org/>
# .. SPDX-License-Identifier: GPL-3.0-only

# .. _java__ref_defaults:

# debops.java default variables [[[
# =================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../../includes/global.rst


# Java APT packages [[[
# ---------------------

# .. envvar:: java__install_jdk [[[
#
# By default the role installs only the Java Runtime Environment (JRE)
# packages. Other Ansible roles can request installation of the compatible Java
# Development Kit (JDK) by enabling this variable.
java__install_jdk: False

                                                                   # ]]]
# .. envvar:: java__base_packages [[[
#
# List of default APT packages which should be installed for Java Runtime
# Environment.
java__base_packages: [ 'default-jre-headless', 'ca-certificates-java' ]

                                                                   # ]]]
# .. envvar:: java__jdk_packages [[[
#
# List of default APT packages which should be installed for Java Development
# Kit.
java__jdk_packages: '{{ ([ "default-jdk" ]
                         if (ansible_distribution_release in [ "trusty" ])
                         else [ "default-jdk-headless" ])
                        if java__install_jdk|bool else [] }}'

                                                                   # ]]]
# .. envvar:: java__packages [[[
#
# List of APT packages which should be installed on all hosts in Ansible
# inventory.
java__packages: []

                                                                   # ]]]
# .. envvar:: java__group_packages [[[
#
# List of APT packages which should be installed on a group of hosts in Ansible
# inventory.
java__group_packages: []

                                                                   # ]]]
# .. envvar:: java__host_packages [[[
#
# List of APT packages which should be installed on specific hosts in Ansible
# inventory.
java__host_packages: []

                                                                   # ]]]
# .. envvar:: java__dependent_packages [[[
#
# List of APT packages requested by other Ansible roles.
java__dependent_packages: []

                                                                   # ]]]
# .. envvar:: java__alternatives [[[
#
# Set java alternatives.
java__alternatives: ''
                                                                   # ]]]
                                                                   # ]]]
                                                                   # ]]]
