---

dependencies:
  - role: debops.ansible_plugins
  - role: debops.secret
  - role: debops.ldap
  - role: debops.postfix


galaxy_info:
  role_name: 'postfix_virtual_ldap'
  author: "Rainer 'rei' Schuth"
  description: 'Configure Postfix to use Virtual Mail users'
  company: 'DebOps'
  license: 'GPL-3.0-only'
  min_ansible_version: '2.7.0'

  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
        - disco
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
